### ISSUE TITLE
Google Pay API V1

### ISSUE THREAD

**Issue by therealsqvad** [charisTheo/react-google-pay-button#1]
Hello. How I can use GPay Api v1. My provider uses API version 1. Your component fails to pay and reports the error '**cardRequirements**' is missing!'. The documentation says that in addition to **allowedPaymentMethods**, you must specify **cardRequirements**. How can I pass this parameter?

**Comment by charisTheo** [comment]
Unfortunately I have built this using the Google Pay API version 2 and with no full backwards compatibility. However as far as I can see you should be able to use this package but following the migration guide from [Google Developers page](https://developers.google.com/pay/api/web/guides/resources/update-to-latest-version).

**Comment by charisTheo** [comment]
Hi @therealsqvad have you been able to use the button following the migration guide?

**Comment by therealsqvad** [comment]
Hello @charisTheo , No, unfortunately I was unable to use your component. The migration guide says that the GooglePay API v1 request object must contain fields 
{allowedPaymentMethods: ['CARD', 'TOKENIZED_CARD'], cardRequirements: { allowedCardNetworks: ['AMEX', 'MASTERCARD', 'VISA'] };
But if I pass in props to GPayButton cardRequirements - it is ignored.

**Comment by therealsqvad** [comment]
I also tried using the GooglePay API v2 test environment to test your component. I am trying to call onPaymentAuthorized with parameters from my state, but they are undefined in this callback, how can I use the token received from the GooglePay API in conjunction with data from state?

**Comment by charisTheo** [comment]
> I also tried using the GooglePay API v2 test environment to test your component. I am trying to call onPaymentAuthorized with parameters from my state, but they are undefined in this callback, how can I use the token received from the GooglePay API in conjunction with data from state?

You can use the [bind method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) to prepend arguments to the handler function.

```
<GPayButton
  onPaymentAuthorized={this.paymentAuthorizedHandler.bind(this, copyOfYourState)}
  ...
```

Then you should get the arguments later in the implementation of your handler function:

```
paymentAuthorizedHandler = (copyOfYourState, paymentData) => {
  copyOfYourState // the state at the point of rendering the button
  this.state // your current state
  ...
}
```

**Comment by therealsqvad** [comment]
It was not required. **React hooks** are to blame. When using the class, the function handler sees the values from props, and when using functional component, the values from state in the callback were undefined. 

As for the GooglePay API v1, I had to implement my own component for specifying the **cardRequirements** parameter, according to the documentation

Thanks for the help
